# Site
name: 'Alexturtleneckk'
description: 'Mundana is a free Jekyll theme for awesome people like you, Medium like.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
url : 'https://alexturtleneckk.github.io'
baseurl: ''
disqus: 'demowebsite'
email: 'khy8387@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
About ME:
    Alex:
      name:           HeeYeon Kwon
      site:           https://github.com/alexturtleneckk
      avatar:         /assets/images/ProfilePic.jpg
      bio:            "Hi, I am Alex, pharmacist trying to be a data anaylst for Medicine AI."
      email:          khy8387@gmail.com
      #instagram:        https://instagram.com/heeyeo_on

    # jane:
    #   name:           Jane
    #   site:           https://www.wowthemes.net
    #   avatar:         /assets/images/avatar2.jpg
    #   bio:            "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
    #   email:          fakemail@gmail.com
    #   twitter:        https://twitter.com/wowthemesnet
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: HeeYeon Kwon
      avatar: /assets/images/ProfilePic.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# category_archives:
#   type: liquid
#   path: /categories/

# tag_archive:
#   type: liquid
#   path: /tags/

# jekyll_archives:
#   enabled:
#     - categories
#     - tags

#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]

navigation:
  - title: Contact
    url: "{{ site.baseurl }}/contact.html"
  - title: ML
    url: "{{ site.baseurl }}/categories/ML.html"
  - title: CV
    url: "{{ site.baseurl }}/categories/CV.html"
  - title: NLP
    url: "https://alexturtleneckk.github.io/categories.html#NLP"
  - title: PaperReview
    url: "https://alexturtleneckk.github.io/categories.html#PaperReview"

